### ISSUE TITLE
some problem with encode

### ISSUE THREAD

**Issue by qwescin** [jlmadurga/django-telegram-bot#10]
Hi, in python 3.4.2 id have some problem fith encode template_commands.txt.
In bot_views\generic\base.py :
`bot.send_message(chat_id=update.message.chat_id, text=text.encode('utf-8'), reply_markup=keyboard, parse_mode=ParseMode.MARKDOWN)`
after run we have
`raise TypeError(repr(o) + " is not JSON serializable")`

cause after encode we have text like    `b'sometext'`
I find temporary solution 
`bot.send_message(chat_id=update.message.chat_id, text=text, reply_markup=keyboard, parse_mode=ParseMode.MARKDOWN)`
Maybe you find the best solution better than me, im just novice in python =)
sry for bad english.

**Comment by jlmadurga** [comment]
Thanks to @mhsekhavat .
Released in 0.5.1
