### ISSUE TITLE
'telegrambot' is not a registered namespace

### ISSUE THREAD

**Issue by Arsaev** [jlmadurga/django-telegram-bot#21]
Return this error when i try to create new bot
`NoReverseMatch at /admin/telegrambot/bot/add/
'telegrambot' is not a registered namespace`

**Comment by fams** [comment]
Have you configured the applications?
    'telegrambot',
    'rest_framework',
    'django.contrib.sites',

and defined site_ID?
SITE_ID = 1

**Comment by fams** [comment]
e tambem
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^telegrambot/', include('telegrambot.urls', namespace="telegrambot")),
]
