### ISSUE TITLE
Could you provide some examples?

### ISSUE THREAD

**Issue by zavod** [jlmadurga/django-telegram-bot#9]
Hello! Thank you for your rep. It doesn't work on my site. Could you provide work example around webhook?

**Comment by jlmadurga** [comment]
You have a demo here:
https://github.com/jlmadurga/django-telegram-bot-demo

2016-04-14 7:21 GMT+02:00 zavod <notifications@github.com>:

> Hello! Thank you for your rep. It doesn't work on my site. Could you
> provide work example around webhook?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jlmadurga/django-telegram-bot/issues/9>
>



-- 
Juan Lucas Madurga Martín-Serrano
Madrid Spain
